"""001_baseline_worldwild_schema

Revision ID: b17f6abc63d9
Revises:
Create Date: 2026-04-28 11:38:50.839148
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b17f6abc63d9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapter_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("offers_fetched", sa.Integer(), nullable=False),
        sa.Column("offers_new", sa.Integer(), nullable=False),
        sa.Column("offers_pre_filtered_out", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adapter_runs_source"), "adapter_runs", ["source"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_offer_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("promoted_to_neon_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decisions_job_offer_id"), "decisions", ["job_offer_id"], unique=False)
    op.create_table(
        "job_offers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=8), nullable=True),
        sa.Column("contract_type", sa.String(length=32), nullable=True),
        sa.Column("contract_time", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pre_filter_passed", sa.Boolean(), nullable=False),
        sa.Column("pre_filter_reason", sa.String(length=255), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_offers_company"), "job_offers", ["company"], unique=False)
    op.create_index(op.f("ix_job_offers_content_hash"), "job_offers", ["content_hash"], unique=False)
    op.create_index(op.f("ix_job_offers_pre_filter_passed"), "job_offers", ["pre_filter_passed"], unique=False)
    op.create_index(op.f("ix_job_offers_source"), "job_offers", ["source"], unique=False)
    op.create_index("ix_job_offers_source_external_id", "job_offers", ["source", "external_id"], unique=True)
    op.create_index("ix_job_offers_source_ingested_at", "job_offers", ["source", "ingested_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_offers_source_ingested_at", table_name="job_offers")
    op.drop_index("ix_job_offers_source_external_id", table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_source"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_pre_filter_passed"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_content_hash"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_company"), table_name="job_offers")
    op.drop_table("job_offers")
    op.drop_index(op.f("ix_decisions_job_offer_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_adapter_runs_source"), table_name="adapter_runs")
    op.drop_table("adapter_runs")
    # ### end Alembic commands ###
